<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-30T23:28:14 IST" name="Suite" finished-at="2023-04-30T23:29:15 IST" duration-ms="61134">
    <groups>
    </groups>
    <test started-at="2023-04-30T23:28:14 IST" name="Test" finished-at="2023-04-30T23:29:15 IST" duration-ms="61134">
      <class name="Test.ArkFramWork.LoginTest">
        <test-method is-config="true" signature="openUrl()[pri:0, instance:Test.ArkFramWork.LoginTest@56673b2c]" started-at="2023-04-30T23:28:14 IST" name="openUrl" finished-at="2023-04-30T23:28:26 IST" duration-ms="11974" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openUrl -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Test.ArkFramWork.LoginTest@56673b2c]" started-at="2023-04-30T23:28:26 IST" name="login" data-provider="getLoginData" finished-at="2023-04-30T23:28:34 IST" duration-ms="8319" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[veer@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Successfull]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Test.ArkFramWork.LoginTest@56673b2c]" started-at="2023-04-30T23:28:34 IST" name="tearDown" finished-at="2023-04-30T23:28:34 IST" duration-ms="321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="openUrl()[pri:0, instance:Test.ArkFramWork.LoginTest@56673b2c]" started-at="2023-04-30T23:28:34 IST" name="openUrl" finished-at="2023-04-30T23:28:40 IST" duration-ms="5331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openUrl -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Test.ArkFramWork.LoginTest@56673b2c]" started-at="2023-04-30T23:28:40 IST" name="login" data-provider="getLoginData" finished-at="2023-04-30T23:28:58 IST" duration-ms="18061" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[vejyar@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[45676]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[faliure]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test.ArkFramWork.LoginTest.login(LoginTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Test.ArkFramWork.LoginTest@56673b2c]" started-at="2023-04-30T23:28:58 IST" name="tearDown" finished-at="2023-04-30T23:28:58 IST" duration-ms="348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Test.ArkFramWork.LoginTest -->
      <class name="Test.ArkFramWork.ThreeTest">
        <test-method signature="threeTest()[pri:0, instance:Test.ArkFramWork.ThreeTest@35432107]" started-at="2023-04-30T23:29:07 IST" name="threeTest" finished-at="2023-04-30T23:29:14 IST" duration-ms="7482" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test.ArkFramWork.ThreeTest.threeTest(ThreeTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Test.ArkFramWork.ThreeTest@35432107]" started-at="2023-04-30T23:29:14 IST" name="tearDown" finished-at="2023-04-30T23:29:15 IST" duration-ms="248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Test.ArkFramWork.ThreeTest -->
      <class name="Test.ArkFramWork.TwoTest">
        <test-method signature="twoTest()[pri:0, instance:Test.ArkFramWork.TwoTest@3adcc812]" started-at="2023-04-30T23:28:58 IST" name="twoTest" finished-at="2023-04-30T23:29:06 IST" duration-ms="7996" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- twoTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Test.ArkFramWork.TwoTest@3adcc812]" started-at="2023-04-30T23:29:06 IST" name="tearDown" finished-at="2023-04-30T23:29:07 IST" duration-ms="268" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Test.ArkFramWork.TwoTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
